import 'dart:convert';
import 'dart:typed_data';

import 'package:file_picker/file_picker.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/math_workload.dart';

enum MathReportFormat { csv, json, text, pdf }

class MathReportExportService {
  static String render(MathSession session, MathReportFormat format) =>
      switch (format) {
        MathReportFormat.json => const JsonEncoder.withIndent(
          '  ',
        ).convert(session.toJson()),
        MathReportFormat.csv => _csv(session),
        MathReportFormat.text => _text(session),
        MathReportFormat.pdf => throw ArgumentError(
          'Use renderPdf for mathematical PDF reports',
        ),
      };

  static Future<Uint8List> renderPdf(MathSession session) async {
    final result = session.result;
    final rows = [
      for (final task in result.tasks)
        [
          task.taskId,
          task.start,
          task.count,
          result.results
              .firstWhere((item) => item.taskId == task.taskId)
              .values,
        ],
    ];
    final document = pw.Document();
    document.addPage(
      pw.MultiPage(
        build: (context) => [
          pw.Header(level: 0, child: pw.Text('SWARM MESH mathematical report')),
          pw.Text(
            _pdfProblemName(session.problem),
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Session: ${session.id}'),
          pw.Text('UTC: ${session.createdAt.toUtc().toIso8601String()}'),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            headers: const ['Metric', 'Value'],
            data: [
              ['Distributed mode', result.mode],
              ['Tasks', result.tasks.length],
              ['Correctness match', session.correctnessMatch ? 'Yes' : 'No'],
              ['Single-device time', _milliseconds(session.baseline)],
              ['Distributed time', _milliseconds(result)],
              [
                'Speedup',
                session.speedup?.toStringAsFixed(2) ?? 'Not applicable',
              ],
              ['Contributions', result.contributions],
              ['Retries', result.retries],
              ['Bytes sent', result.sentBytes],
              ['Bytes received', result.receivedBytes],
              ['Aggregate result', result.summary],
            ],
            cellStyle: const pw.TextStyle(fontSize: 8),
            headerStyle: pw.TextStyle(
              fontSize: 8,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 14),
          pw.Header(level: 1, child: pw.Text('Task results')),
          pw.TableHelper.fromTextArray(
            headers: const ['Task', 'Start', 'Count', 'Result'],
            data: rows,
            cellStyle: const pw.TextStyle(fontSize: 7),
            headerStyle: pw.TextStyle(
              fontSize: 7,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Mathematical result generated by deterministic local task execution.',
            style: const pw.TextStyle(color: PdfColors.grey),
          ),
        ],
      ),
    );
    return document.save();
  }

  static Future<Uri?> save(MathSession session, MathReportFormat format) async {
    final extension = format == MathReportFormat.text ? 'txt' : format.name;
    final bytes = format == MathReportFormat.pdf
        ? await renderPdf(session)
        : Uint8List.fromList(utf8.encode(render(session, format)));
    return FilePicker.saveFile(
      fileName: 'swarm-mesh-math-${session.id}.$extension',
      bytes: bytes,
      mimeType: switch (format) {
        MathReportFormat.json => 'application/json',
        MathReportFormat.csv => 'text/csv',
        MathReportFormat.text => 'text/plain',
        MathReportFormat.pdf => 'application/pdf',
      },
    );
  }

  static String _csv(MathSession session) {
    final lines = <List<Object?>>[
      [
        'record_type',
        'session_id',
        'problem',
        'task_id',
        'start',
        'count',
        'values',
      ],
      for (final task in session.result.tasks)
        [
          'task',
          session.id,
          session.problem.id,
          task.taskId,
          task.start,
          task.count,
          jsonEncode(
            session.result.results
                .firstWhere((item) => item.taskId == task.taskId)
                .values,
          ),
        ],
      [
        'summary',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        jsonEncode(session.result.summary),
      ],
      [
        'baseline_microseconds',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.baseline.elapsed.inMicroseconds,
      ],
      [
        'distributed_microseconds',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.result.elapsed.inMicroseconds,
      ],
      [
        'correctness_match',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.correctnessMatch,
      ],
      ['speedup', session.id, session.problem.id, '', '', '', session.speedup],
      [
        'contributions',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        jsonEncode(session.result.contributions),
      ],
      [
        'retries',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.result.retries,
      ],
      [
        'sent_bytes',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.result.sentBytes,
      ],
      [
        'received_bytes',
        session.id,
        session.problem.id,
        '',
        '',
        '',
        session.result.receivedBytes,
      ],
    ];
    return '${lines.map((row) => row.map(_cell).join(',')).join('\r\n')}\r\n';
  }

  static String _text(MathSession session) {
    final output = StringBuffer()
      ..writeln('SWARM MESH MATHEMATICAL REPORT')
      ..writeln('Problem: ${session.problem.title}')
      ..writeln('Session: ${session.id}')
      ..writeln('UTC: ${session.createdAt.toUtc().toIso8601String()}')
      ..writeln('Result: ${jsonEncode(session.result.summary)}')
      ..writeln('Correctness match: ${session.correctnessMatch}')
      ..writeln('Single-device: ${_milliseconds(session.baseline)}')
      ..writeln('Distributed: ${_milliseconds(session.result)}')
      ..writeln(
        'Speedup: ${session.speedup?.toStringAsFixed(2) ?? 'not applicable'}',
      )
      ..writeln('Contributions: ${session.result.contributions}')
      ..writeln('Retries: ${session.result.retries}')
      ..writeln(
        'Bytes sent/received: ${session.result.sentBytes}/${session.result.receivedBytes}',
      )
      ..writeln('\nTask results:');
    for (final task in session.result.tasks) {
      final result = session.result.results.firstWhere(
        (item) => item.taskId == task.taskId,
      );
      output.writeln(
        '${task.taskId} (${task.count} items): ${jsonEncode(result.values)}',
      );
    }
    return output.toString();
  }

  static String _cell(Object? value) {
    final text = value?.toString() ?? '';
    return '"${text.replaceAll('"', '""')}"';
  }

  static String _milliseconds(MathRunResult result) =>
      '${(result.elapsed.inMicroseconds / 1000).toStringAsFixed(2)} ms';

  static String _pdfProblemName(MathProblem problem) =>
      problem == MathProblem.monteCarloPi ? 'Monte Carlo pi' : problem.title;
}
